apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotibot-api-gateway
  labels:
    app: emotibot-api-gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emotibot-api-gateway
  template:
    metadata:
      labels:
        app: emotibot-api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: kong:3.4
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8001
          name: admin
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000"
        - name: KONG_LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "512Mi"
        volumeMounts:
        - name: kong-config
          mountPath: /kong.yml
          subPath: kong.yml
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotibot-auth-service
  labels:
    app: emotibot-auth-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emotibot-auth-service
  template:
    metadata:
      labels:
        app: emotibot-auth-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: auth-service
        image: europe-west1-docker.pkg.dev/emotibot-project-463521/emotibot-repo/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: AUTH_DATABASE_URL
          value: "postgresql://postgres:emotibot-auth-db1@127.0.0.1:5432/emotibotdb"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: secret-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: jwt-secret-key
        - name: SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: service-secret
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
        command:
          - "/cloud_sql_proxy"
          - "-instances=emotibot-project-463521:europe-west1:emotibot-auth-db=tcp:5432"
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotibot-emotion-service
  labels:
    app: emotibot-emotion-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emotibot-emotion-service
  template:
    metadata:
      labels:
        app: emotibot-emotion-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: emotion-service
        image: europe-west1-docker.pkg.dev/emotibot-project-463521/emotibot-repo/emotion-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: AUTH_SERVICE_URL
          value: "http://emotibot-auth-service:8002"
        - name: SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: service-secret
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotibot-conversation-service
  labels:
    app: emotibot-conversation-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emotibot-conversation-service
  template:
    metadata:
      labels:
        app: emotibot-conversation-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: conversation-service
        image: europe-west1-docker.pkg.dev/emotibot-project-463521/emotibot-repo/conversation-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
          name: http
        env:
        - name: CONVERSATION_DATABASE_URL
          value: "postgresql://postgres:emotibot-conversation-db1@127.0.0.1:5433/emotibotdb"
        - name: AUTH_SERVICE_URL
          value: "http://emotibot-auth-service:8002"
        - name: EMOTION_SERVICE_URL
          value: "http://emotibot-emotion-service:8003"
        - name: AI_SERVICE_URL
          value: "http://emotibot-ai-service:8005"
        - name: SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: service-secret
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
        command:
          - "/cloud_sql_proxy"
          - "-instances=emotibot-project-463521:europe-west1:emotibot-conversation-db=tcp:5433"
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotibot-ai-service
  labels:
    app: emotibot-ai-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emotibot-ai-service
  template:
    metadata:
      labels:
        app: emotibot-ai-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8005"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ai-service
        image: europe-west1-docker.pkg.dev/emotibot-project-463521/emotibot-repo/ai-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
          name: http
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: gemini-api-key
        - name: AUTH_SERVICE_URL
          value: "http://emotibot-auth-service:8002"
        - name: SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: service-secret
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotibot-websocket-service
  labels:
    app: emotibot-websocket-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emotibot-websocket-service
  template:
    metadata:
      labels:
        app: emotibot-websocket-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8006"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: websocket-service
        image: europe-west1-docker.pkg.dev/emotibot-project-463521/emotibot-repo/websocket-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8006
          name: http
        env:
        - name: AUTH_SERVICE_URL
          value: "http://emotibot-auth-service:8002"
        - name: EMOTION_SERVICE_URL
          value: "http://emotibot-emotion-service:8003"
        - name: AI_SERVICE_URL
          value: "http://emotibot-ai-service:8005"
        - name: SERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: emotibot-secrets
              key: service-secret
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        version: v1
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --appendonly yes
        - --maxmemory 256mb
        - --maxmemory-policy allkeys-lru
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-data
        emptyDir: {}

---
# Frontend Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotibot-frontend
  labels:
    app: emotibot-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emotibot-frontend
  template:
    metadata:
      labels:
        app: emotibot-frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: gcr.io/emotibot-project-463521/emotibot-frontend:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
 