apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: emotibot-frontend
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://emotibot-api-gateway:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            proxy_pass http://emotibot-api-gateway:8000/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /socket.io/ {
            proxy_pass http://emotibot-api-gateway:8000/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  labels:
    app: emotibot-frontend
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EmotiBot - AI Emotional Chatbot</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .container {
                background: rgba(255, 255, 255, 0.95);
                padding: 40px;
                border-radius: 20px;
                box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
                text-align: center;
                max-width: 600px;
                margin: 20px;
            }
            h1 {
                color: #333;
                margin-bottom: 20px;
                font-size: 2.5em;
            }
            .emoji {
                font-size: 4em;
                margin: 20px 0;
            }
            p {
                color: #666;
                font-size: 1.2em;
                line-height: 1.6;
                margin-bottom: 30px;
            }
            .status {
                background: #e8f5e8;
                border: 2px solid #4caf50;
                border-radius: 10px;
                padding: 20px;
                margin: 20px 0;
            }
            .status h3 {
                margin: 0 0 15px 0;
                color: #2e7d32;
            }
            .service-list {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 15px;
                margin-top: 20px;
            }
            .service {
                background: #f8f9fa;
                padding: 15px;
                border-radius: 8px;
                border-left: 4px solid #4caf50;
            }
            .service h4 {
                margin: 0 0 5px 0;
                color: #333;
            }
            .service p {
                margin: 0;
                font-size: 0.9em;
                color: #666;
            }
            .api-links {
                margin-top: 30px;
                padding: 20px;
                background: #f8f9fa;
                border-radius: 10px;
            }
            .api-links h3 {
                margin-top: 0;
                color: #333;
            }
            .api-links a {
                display: inline-block;
                margin: 5px 10px;
                padding: 10px 20px;
                background: #667eea;
                color: white;
                text-decoration: none;
                border-radius: 5px;
                transition: background 0.3s;
            }
            .api-links a:hover {
                background: #5a67d8;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="emoji">🤖💬</div>
            <h1>EmotiBot</h1>
            <p>Welcome to EmotiBot - Your AI-powered emotional chatbot! Our microservices architecture is up and running.</p>
            
            <div class="status">
                <h3>🎉 System Status: Online</h3>
                <div class="service-list">
                    <div class="service">
                        <h4>🔐 Auth Service</h4>
                        <p>User authentication & authorization</p>
                    </div>
                    <div class="service">
                        <h4>😊 Emotion Service</h4>
                        <p>Emotion detection & analysis</p>
                    </div>
                    <div class="service">
                        <h4>💬 Conversation Service</h4>
                        <p>Chat history & management</p>
                    </div>
                    <div class="service">
                        <h4>🧠 AI Service</h4>
                        <p>AI responses via Gemini</p>
                    </div>
                    <div class="service">
                        <h4>🔌 WebSocket Service</h4>
                        <p>Real-time communication</p>
                    </div>
                    <div class="service">
                        <h4>🚪 API Gateway</h4>
                        <p>Kong-powered routing</p>
                    </div>
                </div>
            </div>
            
            <div class="api-links">
                <h3>🔗 API Endpoints</h3>
                <a href="/health" target="_blank">General Health</a>
                <a href="/api/auth/login" target="_blank">Auth Login</a>
                <a href="/api/analyze" target="_blank">Emotion Analyze</a>
                <a href="/api/conversations" target="_blank">Conversations</a>
                <a href="/api/ai/generate" target="_blank">AI Generate</a>
                <a href="/socket.io" target="_blank">WebSocket</a>
            </div>
            
            <p><strong>Kong Admin API:</strong> <a href="http://35.241.206.85:8001" target="_blank">http://35.241.206.85:8001</a></p>
        </div>
    </body>
    </html> 