apiVersion: v1
kind: Secret
metadata:
  name: emotibot-secrets
type: Opaque
data:
  # These are base64 encoded placeholders
  # In production, use actual secrets
  # echo -n "your-secret" | base64
  secret-key: c2VjcmV0X2tleV9jaGFuZ2VfbWVfaW5fcHJvZHVjdGlvbg==
  jwt-secret-key: and0X3NlY3JldF9rZXlfY2hhbmdlX21lX2luX3Byb2R1Y3Rpb24=
  database-url: cG9zdGdyZXNxbDovL2Vtb3RpYm90OnN1cGVyc2VjcmV0cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9lbW90aWJvdGRi
  # Add your Gemini API key here (base64 encoded)
  # echo -n "your_actual_gemini_api_key" | base64
  gemini-api-key: QUl6YVN5RHRTUnJLRm4xR2xYcG9wUjA1d1VOZTdtdl9JODRHZkJR
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # These are base64 encoded placeholders
  postgres-db: ZW1vdGlib3RkYg==
  postgres-user: ZW1vdGlib3Q=
  postgres-password: c3VwZXJzZWNyZXRwYXNzd29yZA== 