apiVersion: v1
kind: Secret
metadata:
  name: emotibot-secrets
  namespace: emotibot-staging
type: Opaque
data:
  # Database passwords (base64 encoded)
  auth-db-password: YXV0aF9zZWN1cmVfcGFzc18yMDI0  # auth_secure_pass_2024
  conv-db-password: Y29udl9zZWN1cmVfcGFzc18yMDI0  # conv_secure_pass_2024
  
  # Application secrets (base64 encoded)
  jwt-secret-key: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS10aGF0LXNob3VsZC1iZS1hdC1sZWFzdC0zMi1jaGFyYWN0ZXJzLWxvbmc=  # your-super-secret-jwt-key-that-should-be-at-least-32-characters-long
  secret-key: eW91ci1zdXBlci1zZWNyZXQtZmxhc2sta2V5LXRoYXQtc2hvdWxkLWJlLWF0LWxlYXN0LTMyLWNoYXJhY3RlcnM=  # your-super-secret-flask-key-that-should-be-at-least-32-characters
  service-secret: eW91ci1zdXBlci1zZWNyZXQtc2VydmljZS1rZXktdGhhdC1zaG91bGQtYmUtYXQtbGVhc3QtMzItY2hhcnM=  # your-super-secret-service-key-that-should-be-at-least-32-chars
  
  # Database connection URLs (base64 encoded)
  auth-database-url: cG9zdGdyZXNxbDovL2F1dGhfdXNlcjphdXRoX3NlY3VyZV9wYXNzXzIwMjRAYXV0aC1kYjo1NDMyL2F1dGhkYg==  # postgresql://auth_user:auth_secure_pass_2024@auth-db:5432/authdb
  conversation-database-url: cG9zdGdyZXNxbDovL2NvbnZfdXNlcjpjb252X3NlY3VyZV9wYXNzXzIwMjRAY29udmVyc2F0aW9uLWRiOjU0MzIvY29udmVyc2F0aW9uZGI=  # postgresql://conv_user:conv_secure_pass_2024@conversation-db:5432/conversationdb
  
  # Redis and API keys (base64 encoded)
  redis-host: cmVkaXM6NjM3OQ==  # redis:6379
  gemini-api-key: QUl6YVN5RHVtbXlLZXlGb3JEZXZlbG9wbWVudFB1cnBvc2Vz  # AIzaSyDummyKeyForDevelopmentPurposes 