version: '3.8'

services:
  # Simple test service - just health checks
  test-service:
    image: python:3.11-slim
    command: >
      sh -c "
        pip install flask requests &&
        python -c '
        from flask import Flask, jsonify
        app = Flask(__name__)
        @app.route(\"/health\")
        def health():
            return jsonify({\"status\": \"healthy\", \"service\": \"test\"})
        @app.route(\"/\")
        def home():
            return jsonify({\"message\": \"EmotiBot Test Service Running\", \"status\": \"ok\"})
        app.run(host=\"0.0.0.0\", port=5000, debug=True)
        '
      "
    ports:
      - "5000:5000"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 