version: '3.8'

services:
  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - test-network
    restart: unless-stopped

  # Auth Service
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - AUTH_DATABASE_URL=sqlite:///auth.db
      - SECRET_KEY=test-secret-key
      - JWT_SECRET_KEY=test-jwt-secret-key
      - SERVICE_SECRET=test-service-secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - test-network
    restart: unless-stopped

  # Emotion Service
  emotion-service:
    build:
      context: ./emotion-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8002
      - SERVICE_SECRET=test-service-secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - auth-service
      - redis
    networks:
      - test-network
    restart: unless-stopped

networks:
  test-network:
    driver: bridge 