name: CI/CD with Docker Compose Deployment

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ... same code-quality, test, build, and security-scan jobs as simplified version ...
  
  # Deploy to staging server using Docker Compose
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    if: github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to staging server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        script: |
          cd /path/to/your/app
          git pull origin main
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
          echo "FLASK_ENV=staging" >> .env
          docker-compose down
          docker-compose pull
          docker-compose up -d
          
          # Wait for health check
          sleep 30
          curl -f http://localhost:5001/health || exit 1 